### ISSUE TITLE
Using sms verification disable the possibility to change the signature

### ISSUE THREAD

**Issue by geoffreyIOOF** [docusign/code-examples-java#14] opened 2021-09-17 03:14 UTC
Hi,
I had this problem for quite some time now.

When we use SMS verification with the imbedded signing it is preventing the user to change its signature.
When not using the SMS verification the user can change its signature as expected. (We need sms verification )

This feature is not accessible when using the SMS verification
![image](https://user-images.githubusercontent.com/82996400/133717532-c3c459a4-dbe1-4440-9612-9bd0dda82708.png)

To reproduce this behavior please add the following in the method makeEnvelope of EG001ControllerEmbeddedSigning
        final List<String> RECIPIENT_PHONE_NUMBERS = Arrays.asList( YOUR PHONE NUMBER );
        final RecipientSMSAuthentication smsAuth = new RecipientSMSAuthentication();
        smsAuth.setSenderProvidedNumbers( RECIPIENT_PHONE_NUMBERS );
        signer.setSmsAuthentication( smsAuth );
        signer.setIdCheckConfigurationName( "SMS Auth $" );

Then try 1. Use embedded signing and will see that you can't change your signature once you adopted one.
![image](https://user-images.githubusercontent.com/82996400/133717767-731a6ac5-c544-4b90-ab2b-92c229528682.png)

**I am doing something wrong that prevent me to change my signature when using the SMS verification?**

**Is there any work around to get this functionality back when using the SMS verification ?**

Our customers don't have a docusign account.
Possible work around :
**Is there a way to remove the signature adoption of a signer via the API or via the Admin page? SO the next time they sign a document they have to select a signature adoption ?**

Kind regards

**Comment by InbarGazit** [comment] 2022-01-28 22:49
Is this issue related to the Java code examples? do you see this issue without using the API?

**Comment by geoffreyIOOF** [comment] 2022-01-31 07:34
Hi , thank you for looking at this issue. 
I am using the java SDK in our test and prod and I have the same problem. Not sure what do you mean by "do you see this issue without using the API? " (no I didnt try to use the rest api, to see if I get the same result.)

Let me know if you need more information but I think my original post give all the details to reproduce the problem.

Kind regards

**Comment by InbarGazit** [comment] 2022-01-31 16:56
You are trying to use SMS verification and it doesn't work? is that the issue? are you doing it from the API? can you do it from the web app?

**Comment by geoffreyIOOF** [comment] 2022-02-03 04:58
SMS Verification works. but when I use the SMS verification I don't have the option to change my signature.

I ll try from the webapp soon.

**Comment by geoffreyIOOF** [comment] 2022-02-03 05:16
Hi I just did the test using the webapp and I get the same problem.
When signing a document USING the SMS verification the option to change my signature is NOT AVAILABLE (Clicking on my signature remove the signature)

When signing a document NOT USING the SMS verification the option to change my signature is AVAILABLE (Clicking on my signature shows a drop down menu to remove or change my signature)

**Comment by InbarGazit** [comment] 2022-02-03 16:49
Is this the old or new SMS verification? This may be "by design" but even if it's a bug - unrelated to the API.

**Comment by geoffreyIOOF** [comment] 2022-02-04 03:42
How would I know if it s the old or new SMS verification?
Yeah it may not be related with the API. 
I already raised multiple bug through the Docusign Support but even when the support acknowledge it s bug, it never get fixed...

**Comment by InbarGazit** [comment] 2022-02-04 22:57
If you have bug numbers - let me know and I can check, otherwise, I'll probably close this issue as it's unrelated to the Java code we have in here.

**Comment by geoffreyIOOF** [comment] 2022-02-14 23:23
Hi, is there any progress on TIERBUGS-25417 ?
That s the issue that has been raised 10 months ago. 

Thanks

**Comment by InbarGazit** [comment] 2022-02-14 23:38
Hello, our support engineers were not able to reproduce this issue.
You may need to contact support.docusign.com and open a case and try to work with them to see why you're seeing this problem.

**Comment by geoffreyIOOF** [comment] 2022-02-14 23:42
I also tried with the web app and the issue is there.

Are you saying the status of TIERBUGS-25417 is (can't reproduce ?)

**Comment by InbarGazit** [comment] 2022-02-14 23:44
Yes, this ticket was closed on May of last year with lack of clarification about how to see the issue.

**Comment by geoffreyIOOF** [comment] 2022-02-14 23:56
Thank you for the update.
Dealing with the DocuSign support is so frustrating...

**Closed** 2022-03-24 17:28 UTC
